name: slf-zonal-stats
channels:
  - conda-forge

dependencies:
  - python=3.11
  - geopandas
  - rasterio
  - rioxarray
  - pyproj
  - gdal
  - fiona
  - shapely
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
